build:
  version: "3.0"

accounts:
  message: "Welcome to DEFAULT account service"
  contactDetails:
    name: "Rahul Sohal-Architect"
    email: "rahulsohal@mail.com"
  onCallSupport:
    - 99929384929
    - 94983892929
