build:
  version: "1.0"
accounts:
  message: "Welcome to the PROD account service"
  contactDetails:
    name: "Product Owner"
    email: "rahulsohal@mail.com"
  onCallSupport:
    - 78729384929
    - 77783892929
