build:
  version: 2.1
cards:
  message: "Welcome to the Cards quality assurance service"
  contactDetails:
    name: "Raj Verma"
    email: "raj@mail.com"
  onCallSupport:
    - (545) 777-969
    - (545) 777-968
