build:
  version: 2.0

loans:
  message: "Welcome to quality assurance Loans service"
  contactInfoDetails:
    name: "Carol Saunders"
    email: "carol@mail.com"
  onCallSupport:
    - (321) 204-052
    - (321) 204-055
