build:
  version: 1.1

loans:
  message: "Welcome to PROD Loans service"
  contactInfoDetails:
    name: "Piyush Gulati"
    email: "piyush@mail.com"
  onCallSupport:
    - (124) 761-153
    - (121) 015-815
